### DISCUSSION TITLE
List of current used/maintained Sloth fork features

### DISCUSSION THREAD

**Discussion by slok** [slok/sloth#560] [General]
This is a centralized list of features that have been implemented  (**and continue being used/maintained**) in various Sloth forks during the two years of inactivity in the upstream project.

The goal is to gather them all in one place, review which ones make sense to include in Sloth, and take action accordingly.

I started the list with the ones that I'm aware, but feel free to comment here others so I can add them to the list. Thanks! 🙇 

* 🦥 https://github.com/linode-obs/sloth (@cxdy, @wbollock)
	* [x] Custom info labels: https://github.com/linode-obs/sloth/pull/4 -> https://sloth.dev/slo-plugins/contrib/info_labels_v1/
	* [x] Rule group interval: https://github.com/linode-obs/sloth/pull/1 (https://github.com/slok/sloth/pull/515) -> https://sloth.dev/slo-plugins/contrib/rule_intervals_v1/
* 🦥 https://github.com/kolonialno/sloth (@gbbirkisson)
	* [x] Denominator corrected: https://github.com/kolonialno/sloth/pull/7/files -> https://sloth.dev/slo-plugins/contrib/denominator_corrected_rules_v1/
	* ~Fix label value changes: https://github.com/kolonialno/sloth/pull/6~ -> not porting unless someone is interested.
* 🦥 https://github.com/ostrovok-tech/sloth (@nixargh, @aka-switch)
	*  [x] Victoria metrics support -> https://sloth.dev/slo-plugins/contrib/validate_victoria_metrics_v1/

**Comment by nixargh** [comment]
Hi!
Glad to see you're back in business :)
It would be nice to have all these changes bundled together. Maybe my VictoriaMetrics validation is too straightforward to take it as is, but if I may help somehow, please feel free to ping me.

**Reply by slok** [reply]
Hey! 👋 Thanks!

Yes, I’ll make an announcement for contributors once Sloth is ready. Right now, I’m already working on a refactor to make Sloth more pluggable and easier to contribute to. The idea is to eventually delegate parts of the support and maintenance to others who want to get involved in the project 😄.

**Reply by slok** [reply]
@nixargh / @aka-switch Hi there! 👋  Could you share an example of a working victoria-metrics SLO spec that fails with Sloth upstream please? thanks! 🙇

**Reply by nixargh** [reply]
@slok hi!
The need came from the fact that some development teams use VictoriaMetrics go library instead of Prometheus one and by default the VM lib generates [histograms](https://pkg.go.dev/github.com/VictoriaMetrics/metrics#Histogram) with fluid buckets set. So we were looking for a way to use them and came to the solution below, which uses VM function `histogram_share`.

Here is an example of Sloth config:
```yaml
version: prometheus/v1
service: foo-bar
labels:
  owner: foo
  repo: content/foo-bar
  generated: true
  type: latency
  application: slowpoke
slos:
- name: grpc-latency-percentile-90
  objective: 90
  description: '"grpc" 90 percentile Latency SLO for grade "A"'
  labels:
    actual_grade: A
    target_grade: A
    actual_le: 0.2
    target_le: 0.2
  sli:
    events:
      error_query: 1 - histogram_share(0.2, sum by (vmrange) (rate(requests_duration_seconds_bucket{container_name="foo-bar-grpc", agent_dc="dc_sl"}[{{.window}}])))
      total_query: vector(1)[{{.window}}]
  alerting:
    name: slo_foo-bar_grpc-latency-percentile-90_fail
    labels:
      objective: 90
      objective_reversed: 10
- name: grpc-latency-percentile-99
  objective: 99
  description: '"grpc" 99 percentile Latency SLO for grade "A"'
  labels:
    actual_grade: A
    target_grade: A
    actual_le: 0.4
    target_le: 0.4
  sli:
    events:
      error_query: 1 - histogram_share(0.4, sum by (vmrange) (rate(requests_duration_seconds_bucket{container_name="foo-bar-grpc", agent_dc="dc_sl"}[{{.window}}])))
      total_query: vector(1)[{{.window}}]
  alerting:
    name: slo_foo-bar_grpc-latency-percentile-99_fail
    labels:
      objective: 99
      objective_reversed: 1
```

**Reply by aka-switch** [reply]
Thanks. I actually don't have any ready-to-go interpretation of Victoria Metrics in SLOth on my side or use what @nixargh has done. I just planned to do it. So, unfortunately, I have no code to offer as a PR for now. But let me know if I can help anyway.

**Reply by slok** [reply]
Awesome! thanks @nixargh!

NP @aka-switch, With @nixargh's example should be more than enough for the tests :)

Thanks both 👌

**Comment by cxdy** [comment]
For Linode's usecase, both of our features are necessary for us to be able to switch back to upstream and personally I think they're nice to have even if they go unused. 

Regarding dynamic rule intervals, I have a PR open to extend that to the Kubernetes spec but I just need to add tests. https://github.com/linode-obs/sloth/pull/24 

Happy to get these PRs in for upstream too. I think @wbollock might have a couple PRs in the upstream repo too.

**Reply by cxdy** [reply]
Thanks again Xabier, glad to have some activity over here again!

**Reply by slok** [reply]
Thanks Cody! Good info 🙇. Sadly with the refactor (its for the greater good 😄), the complex PRs like those would need to be rewritten, I can help with those or even try porting them to the new codebase when the time comes 🙏.

**Reply by dekarl** [reply]
Great to see some action.

Seeing you are adding things to the sloth_slo_info, I was wondering how I can get the SLO's description to the Grafana dashboard.

Am I missing something or is the description going nowhere currently? Would this be a common use case where you accept contributions?

**Reply by slok** [reply]
Hey @dekarl,

We haven’t yet decided what will be included in Sloth or how (I'm currently refactoring to make it easier). When the forks were created, each team/individual/company made decisions based on their own needs, but the upstream project is different, since it’s meant to serve a broader set of users. That means we need to be thoughtful about what we add to avoid falling into the [second system effect](https://en.wikipedia.org/wiki/Second-system_effect).

It sounds like you’re particularly interested in the custom info labels feature, right? That’s a useful datapoint, and exactly why we moved this conversation to a discussion: to gather input and understand what people actually need.

**Reply by ishantanu** [reply]
We've internally added `sloth_slo_description` label to `sloth_slo_info` metric amongst other labels (for example `sloth_sli_plugin_id` to track plugin usage) . The only difference is instead of fetching plugin id hardcoded in the manifest, we do it via `spec.SLOs` struct.

**Reply by slok** [reply]
Hey folks! 👋

I’m wrapping up the big refactoring in Sloth that introduces a new extensibility SLO system: **The SLO plugins**. This lets you chain multiple external Go plugins to customize how Sloth generates SLOs, similar approach to how SLI plugins work today, but for the full SLO rule generation pipeline.

If you're interested in testing this out and sharing feedback, I'd really appreciate the help!

For now, there’s no official documentation yet (coming soon!) and only the regular YAML spec supports SLO plugins (not CRDs)

You can use the [latest container](https://github.com/slok/sloth/commit/3c0615e6df0bb55319cf4d9166cace93ee8b5057)  (Use this specific version please, as I may change things like the plugins spec during these days):

```bash
docker pull ghcr.io/slok/sloth:3c0615e6df0bb55319cf4d9166cace93ee8b5057
```

These are some plugins  that are based on the ideas from Linode’s Sloth fork:

- [Rule Intervals Plugin](https://github.com/slok/sloth-test-slo-plugins/tree/main/plugins/rule_intervals_v1)
- [Info Labels Plugin](https://github.com/slok/sloth-test-slo-plugins/tree/main/plugins/info_labels_v1)

Clone the test plugins repo [here](https://github.com/slok/sloth-test-slo-plugins). Then pass the plugins directory to Sloth using the same approach as SLI plugins.

Play around, break stuff, and let me know what you find! Your input is super helpful as I finalize the first release with plugin support.

Thanks in advance! 🦥

Execution example:

```bash
sloth generate -i ./path/to/some-slo.yaml  -m /path/to/sloth-test-slo-plugins/plugins/
```

Example to use the plugins:

```yaml
version: "prometheus/v1"
service: "myservice"
labels:
  owner: "myteam"
  repo: "myorg/myservice"
  tier: "2"
slo_plugins:
  chain:
    - id: github.com/slok/sloth-test-slo-plugins/info_labels/v1
      config:
        labels:
          k1: "v2"
    - id: github.com/slok/sloth-test-slo-plugins/rule_intervals/v1
      config:
        interval:
          default: 15m
          alert: 2m
slos:
  # We allow failing (5xx and 429) 1 request every 1000 requests (99.9%).
  - name: "requests-availability"
    objective: 99.9
    description: "Common SLO based on availability for HTTP request responses."
    plugins:
      chain:
        - id: github.com/slok/sloth-test-slo-plugins/info_labels/v1
          config:
            labels:
              k2: "v3"
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(http_request_duration_seconds_count{job="myservice"}[{{.window}}]))
    alerting:
      name: MyServiceHighErrorRate
      labels:
        category: "availability"
      annotations:
        # Overwrite default Sloth SLO alert summmary on ticket and page alerts.
        summary: "High error rate on 'myservice' requests responses"
      page_alert:
        labels:
          severity: pageteam
          routing_key: myteam
      ticket_alert:
        labels:
          severity: "slack"
          slack_channel: "#alerts-myteam"

```

**Reply by cxdy** [reply]
Oh wow this is awesome. I'll try it out today! Thank you so much.

**Reply by wbollock** [reply]
@slok looks great! Just off-hand, it would be nice to specify unique intervals for specific SLOs in an individual file, as you may have "heavy" SLOs and light SLOs mixed in with the same service. The same goes for the info labels plugin. It tested very well with our existing SLOs though :smile: 

I'm also curious as to your thoughts on what should be a plugin versus going into the main Sloth spec. Regardless the SLO plugins are super powerful and helps us develop new features easily so that's great to have. Do you also envision a single `slok/sloth-slo-plugins` repository to centralize user's plugins, or mainly let people build up their plugins in their own forks?

**Reply by slok** [reply]
Hey @wbollock!

Great questions. Let me try to break everything down.

### Plugin Scope & Flexibility

Plugins can already be declared at both the SLO group level and individual SLO level. The idea is to allow chaining of plugins across levels, Sloth’s default plugins, followed by group-level plugins, and finally SLO-level ones.

```yaml
version: "prometheus/v1"
service: "myservice"
labels:
  owner: "myteam"
  repo: "myorg/myservice"
  tier: "2"
slo_plugins:
  chain:
    - id: github.com/slok/sloth-test-slo-plugins/info_labels/v1
      config:
        labels:
          k1: "v2"
slos:
  # We allow failing (5xx and 429) 1 request every 1000 requests (99.9%).
  - name: "requests-availability"
    objective: 99.9
    description: "Common SLO based on availability for HTTP request responses."
    plugins:
      chain:
      - id: github.com/slok/sloth-test-slo-plugins/rule_intervals/v1
        config:
          interval:
            default: 15m
            alert: 2m
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
# ...
```

What’s more, plugins support a priority field to control execution order. For example, Sloth’s default plugins run at priority: 0, so you can run your plugin earlier by setting a lower value like `-1000`. I have not documented this yet in the examples, but it’s supported.

At some point, I’d also like to allow overriding the default plugin chain entirely. Though I still need to think through the UX for that.

### Spec vs. Plugins

I prefer lean APIs, fewer knobs usually means fewer mistakes and better defaults. If the spec covers ~80% of use cases, that’s good enough for the core. For the rest, plugins give you full freedom to build advanced or highly specific logic without bloating the main config.

**Start edit**

I’d also add that putting features directly into the core tends to be more brittle, slower to evolve, and a lot more work for everyone.

By contrast, plugins are simple, self-contained, and easy to maintain. Contributors do not need to worry about the full Sloth context (like Kubernetes specifics, different Sloth commands, or other internal components). Plugins can be tested in isolation and usually remain small, around 50-200 LoC. which makes them easy to reason about and combine like Lego pieces.

**End edit**

### Centralized Plugins?

I’m still figuring this out. One idea is to keep a `contrib/` folder in the main repo with common plugins (like your interval or info-label ones) maintained by folks willing to provide some level of support.

Alternatively, having an official `slok/sloth-slo-plugins` repo, similar to the SLI plugins,  could make sense too.

Since this does not block plugin usage today, I think we can keep things open and decide based on how the community adopts the SLO plugins and use them.

Of course, things may evolve as we continue testing and gathering feedback, but these are the rough ideas I’m working with right now.

Let me know if I missed anything or if you have further thoughts, really appreciate your input!

There’s nothing fundamentally new in this plugin system 🙂. It’s mostly about taking the best of what has already been proven to work well in other ecosystems. The design is inspired by familiar concepts like Kubernetes CRDs and pod priorities, Traefik’s plugin system, Terraform providers or CoreDNS plugins among others. It’s about applying solid, known patterns to the SLO space to keep things simple, flexible, and predictable.
