### ISSUE TITLE
Quiet services and NaN

### ISSUE THREAD

**Issue by simonjefford** [slok/sloth#133]
I'm wondering what can be done about the scenario where the service has periods of receiving no (or few) requests so NaN values start to creep in.

This is because, for example

```
(sum(rate(http_server_requests_seconds_count{deployment="sloexample"}[1h])))
```

evaluates to 0 so you get NaN when you divide by it to get error ratios.

Normally this is fine - until you come to error budgets. My remaining error budget is not "undefined" or NaN just because my service went quiet for a period of time.

**Comment by slok** [comment]
Hi @simonjefford 

You are right this is not good, is how prometheus works,`NaN != Null != 0`, what you can do to fix this situation is to _only create metrics when you know that the metrics will be valid_, this is when the total events are `>0`. 

So, having this SLO:

```yaml
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(http_request_duration_seconds_count{job="myservice"}[{{.window}}]))
```

Only get SLIs when we can have them:

```yaml
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(http_request_duration_seconds_count{job="myservice"}[{{.window}}])) > 0
```

This way, the total SLI query will return Null (no metrics) when there are no SLOs and there will not be NaNs that corrupt the rules that are created from these SLI metrics.

To test this you could deploy a new SLO with this change along with your current SLO and check if its its working for you while you see both in action.

This is the simplest thing I think it would work, let me know if this works for your use case. If not we can think of a better query using `raw` SLI type (I did this in the past and worked, however is a bit more complex).

If it works with this simple change, I'm wondering if Sloth could do this by default or let the user do this and add to the F.A.Q, not strong opinion at this moment.
