### ISSUE TITLE
Allow 'success_query' on SLO

### ISSUE THREAD

**Issue by warmfusion** [slok/sloth#140]
I'm trying to create a latency based SLO where I want to define an objective of '80% of requests return within 1000m' (for example).

The exporter uses a bucket of 1,000ms to allow me to assign `le="1"` on the query, but I can't work out a clean way to define the equivalent of;

``` yaml
...
spec:
  - name: "service-latency"
    objective: 80
    sli:
      events:
        success_query: sum(rate(service_duration_seconds_bucket{le="1"}[{{.window}}]))
        total_query: sum(rate(service_duration_seconds_bucket{le="+Inf"}[{{.window}}]))
```

As i can't have `success_query` i have to do something odd like this where i take the total over all, take away the group faster than my goal, to obtain the 'out of range' values.

``` yaml
        error_query: |
          sum(rate(service_duration_seconds_bucket{le="+Inf"}[{{.window}}]))
          -
          sum(rate(service_duration_seconds_bucket{le="1"}[{{.window}}]))
        total_query: sum(rate(service_duration_seconds_bucket{le="+Inf"}[{{.window}}]))
```

**Comment by slok** [comment]
Hi @warmfusion!

At this moment I would prefer to not add multiple ways of doing the same thing in the API, mostly to keep it simple, however, I suggest using [`raw`](https://github.com/slok/sloth/tree/main/pkg/prometheus/api/v1#type-sliraw) SLI in this use case, so the query gets simpler:

```yaml
spec:
  - name: "service-latency"
    objective: 80
    sli:
      raw:
        error_ratio_query: |
          1 - (
            sum(rate(service_duration_seconds_bucket{le="1"}[{{.window}}]))
            /
            sum(rate(service_duration_seconds_bucket{le="+Inf"}[{{.window}}]))
          )
```
