### ISSUE TITLE
No data coming for prometheus recording rule  slo:period_error_budget_remaining:ratio

### ISSUE THREAD

**Issue by umakarnati** [slok/sloth#171]
Hi  @slok 
thanks for building awesome tool for tracking SLOs .  I am doing a POC with this tool and facing a issue with metric "slo:period_error_budget_remaining:ratio", its always returning empty data.

<img width="1748" alt="Screen Shot 2021-09-30 at 2 58 54 PM" src="https://user-images.githubusercontent.com/88678165/135536906-86ea8fa8-2a6f-4fc6-b8fb-9676af8af9ba.png">

I assume this is due to  slo:period_burn_rate:ratio, it is referring the  recording rule slo:sli_error:ratio_rate30d  using filter {sloth_id="monitoring-prometheus-adapter-uptime", sloth_service="monitoring", sloth_slo="prometheus-adapter-uptime"}
but slo:sli_error:ratio_rate30d is defined without any such label except sloth_window.

```
- record: slo:period_error_budget_remaining:ratio
    expr: 1 - slo:period_burn_rate:ratio{sloth_id="monitoring-prometheus-adapter-uptime",
      sloth_service="monitoring", sloth_slo="prometheus-adapter-uptime"}
    labels:
      category: prometheus-adapter
      owner: obs-platform
      sloth_id: monitoring-prometheus-adapter-uptime
      sloth_service: monitoring
      sloth_slo: prometheus-adapter-uptime
```

```
 - record: slo:period_burn_rate:ratio
    expr: |
      slo:sli_error:ratio_rate30d{sloth_id="monitoring-prometheus-adapter-uptime", sloth_service="monitoring", sloth_slo="prometheus-adapter-uptime"}
      / on(sloth_id, sloth_slo, sloth_service) group_left
      slo:error_budget:ratio{sloth_id="monitoring-prometheus-adapter-uptime", sloth_service="monitoring", sloth_slo="prometheus-adapter-uptime"}
    labels:
      category: prometheus-adapter
      owner: obs-platform
      sloth_id: monitoring-prometheus-adapter-uptime
      sloth_service: monitoring
      sloth_slo: prometheus-adapter-uptime

```
```
 - record: slo:sli_error:ratio_rate30d
    expr: |
      sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="monitoring-prometheus-adapter-uptime", sloth_service="monitoring", sloth_slo="prometheus-adapter-uptime"}[30d])
      / ignoring (sloth_window)
      count_over_time(slo:sli_error:ratio_rate5m{sloth_id="monitoring-prometheus-adapter-uptime", sloth_service="monitoring", sloth_slo="prometheus-adapter-uptime"}[30d])
    labels:
      sloth_window: 30d
```

Here is my full sloth recording rule file and corresponding generate rules file..
[slothrule.txt](https://github.com/slok/sloth/files/7262809/slothrule.txt)
[generated.txt](https://github.com/slok/sloth/files/7262811/generated.txt)

can you please  check and advice what could be the issue.. thank you..
