### ISSUE TITLE
Grafana dashboard not generates metrics to Burning rate

### ISSUE THREAD

**Issue by Eddie4Frost** [slok/sloth#212]
Hello guys, I hope you are doing great! Can you please help me, where am I going to not generate data from burning rate and Budget?
Thank you in advance!

![grafik](https://user-images.githubusercontent.com/36711905/144084436-374584c0-db14-4ee2-b232-a8b38980abad.png)

![grafik](https://user-images.githubusercontent.com/36711905/144084791-915b7169-c272-4693-924f-304837bcc546.png)

**Comment by slok** [comment]
Hi @Eddie4Frost! 

In order to help you, I need more context :D
- Sloth logs.
- SLO.
- Are the metrics on the prometheus.
- The generated rules are loaded on Prometheus.
- ...

**Comment by Eddie4Frost** [comment]
Hi @slok, my bad! Thank you for your response, below:
The metrics available on Prometheus:
![image](https://user-images.githubusercontent.com/36711905/144302770-0ea5be27-7616-4546-a3c4-76d53d43c53e.png)
The sloth log:
`INFO[0000] SLI plugins loaded                            plugins=0 svc=storage.FileSLIPlugin version=v0.9.0 window=30d
INFO[0000] SLO period windows loaded                     svc=alert.WindowsRepo version=v0.9.0 window=30d windows=2
INFO[0000] Loading Kubernetes configuration...           version=v0.9.0
INFO[0000] Kubernetes controller running                 version=v0.9.0 window=30d
INFO[0000] starting controller                           controller-id=sloth lib=kooper service=kooper.controller version=v0.9.0 window=30d
INFO[0000] Hot-reload http server listening              addr=":8082" version=v0.9.0 window=30d
INFO[0000] Metrics http server listening                 addr=":8081" version=v0.9.0 window=30d
INFO[0000] OS signals listener started                   version=v0.9.0 window=30d
INFO[0000] Hot-reload manager running                    version=v0.9.0 window=30d
INFO[0001] Hot-reload triggered from http webhook        version=v0.9.0 window=30d
INFO[0001] SLI plugins loaded                            plugins=15 svc=storage.FileSLIPlugin version=v0.9.0 window=30d`

The rule:
![image](https://user-images.githubusercontent.com/36711905/144302970-ce550149-2d84-4966-a6ab-bc6eb96e982b.png)

Thank you

**Comment by slok** [comment]
Do other SLOs work for you, or happen on all of them?. Maye it's. just that you aren't burning anything (rare, but who knows...) so there's nothing to chart.

To test, you can use the "fake" plugin to simulate different burn rates:

```yaml
---
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: slo-test
  labels:
    prometheus: prometheus
    role: alert-rules
spec:
  service: "test"
  slos:
    - name: "five-nines"
      objective: 99.999
      sli:
        plugin:
          id: "sloth-common/fake"
          options:
            burn_rate: "0.65"
            jitter_percent: "10"
      alerting:
        name: "TestSLOFiveNinesFailing"
        pageAlert:
          disable: true
        ticketAlert:
          disable: true
```
