### ISSUE TITLE
sli queries status code description in spec

### ISSUE THREAD

**Issue by freeseacher** [slok/sloth#217]
Its  pretty often to exclude some status codes from queries on which slis based on. According to [google video courses on coursera](https://www.coursera.org/lecture/site-reliability-engineering-slos/no-surprises-ydE2H) it is recommended to describe why status codes are excluded. 

Please provide an description field for them. maybe like? 
```
slos:
  # We allow failing (5xx and 429) 1 request every 1000 requests (99.9%).
  - name: "requests-availability"
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
        error_query_clarifications: |
        - 429 -- excluded because of written TOS on api limiting service
        - 503 -- retied by balancer
```

**Comment by slok** [comment]
Hi @freeseacher! You are right that proper documentation of SLOs is required. That's why you have the [slo `description`](https://github.com/slok/sloth/tree/main/pkg/prometheus/api/v1#type-spec) field. I would prefer not to add a new field, that is very coupled to a very specific SLI type when a generic SLO description could have all that information, and more. e.g:

```yaml
slos:
  # 
  - name: "requests-availability"
    description: |
        We allow failing (5xx and 429) 1 request every 1000 requests (99.9%). Error status code clarifications:
        - 429 -- excluded because of written TOS on api limiting service
        - 503 -- retied by balancer
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
```
