### ISSUE TITLE
Sloth Created metrics don't account namespace creating PrometheusRule errors

### ISSUE THREAD

**Issue by daniel-anova** [slok/sloth#270]
When creating two different PrometheusServiceLevel definitions in the different namespace the metrics created by sloth don't account for the namespace causing PrometheusRule evaluation errors.

Example
```yaml
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  labels:
  name: api-slos
  namespace: team_a
spec:
  service: api
  slos:
  - alerting:
      name: SLOApiErrorRate
      pageAlert:
        disable: false
        labels:
          severity: critical
      ticketAlert:
        disable: false
        labels:
          severity: warning
    description: 99.999% of requests must be served with <500 status code.
    labels:
      team: team_a
    name: 99999_http_request_lt_500
    objective: 99.999
    sli:
      events:
        errorQuery: sum(increase(istio_requests_total{destination_workload_namespace="team_a",
          reporter="destination", destination_workload="api",
          response_code=~"5.*"}[{{ .window }}]))
        totalQuery: sum(increase(istio_requests_total{destination_workload_namespace="team_a",
          reporter="destination", destination_workload="api"}[{{
          .window }}]))
---
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  labels:
  name: api-slos
  namespace: team_b
spec:
  service: api
  slos:
  - alerting:
      name: SLOApiErrorRate
      pageAlert:
        disable: false
        labels:
          severity: critical
      ticketAlert:
        disable: false
        labels:
          severity: warning
    description: 99.999% of requests must be served with <500 status code.
    labels:
      team: team_a
    name: 99999_http_request_lt_500
    objective: 99.999
    sli:
      events:
        errorQuery: sum(increase(istio_requests_total{destination_workload_namespace="team_b",
          reporter="destination", destination_workload="api",
          response_code=~"5.*"}[{{ .window }}]))
        totalQuery: sum(increase(istio_requests_total{destination_workload_namespace="team_b",
          reporter="destination", destination_workload="api"}[{{
          .window }}]))
```

When sloth creates the PrometheusRules for these services both add metrics with the same labels causing PrometheusRule evaluation errors.

Currently we're working around by appending the namespace to the service in the PrometheusServiceLevel however it seems a better option to have sloth generate metrics that include the namespace as well.

**Comment by slok** [comment]
Hi @daniel-anova!

I would also suggest adding on the SLO spec a new label at the spec level

```yaml
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  labels:
  name: api-slos
  namespace: team_a
spec:
  service: api
  labels:
    namespace: "team_b"
  slos:
```

However, I would suggest having different IDs as you are doing it. Prometheus doesn't know anything about namespaces and Sloth supports different approaches apart from Kubernetes, so for uniformity reasons it identifies the SLOs by Id
