### ISSUE TITLE
variable grouping

### ISSUE THREAD

**Issue by cznewt** [slok/sloth#277]
Is it possible to make aggregations `by (var)` like for server availability to have `hostname` as grouping key? 

So we can calculate SLO per server? I have done update in queries, the boards not cope with it well, but I'm curious if this can work conceptually, I can update the boards to handle grouping vars.

**Comment by Melodiied** [comment]
//@#Cocaiine#@\\//@#LexZii`มายืนตีเขียด.,*#@\\//@#fOrma๋riin๊z.,*#@\\//@#Melo๋diied#@\\//
***@***.***:6969#@\\//@#www.giithub.com#@\\//@#SOUNEDT-TRAACK-OffMelo
๋diiedffO#@\\\\\\\\\

ในวันที่ จ. 28 มี.ค. 2022 15:05 น. Aleš Komárek ***@***.***>
เขียนว่า:

**Comment by slok** [comment]
Sory for the Spam @cznewt, I already reported to Github.

**Comment by slok** [comment]
Yes, that's something that happens at the Prometheus level. You need to have the correct queries. In the past, I had some custom dashboards for the grouping of some SLOs that I knew they exists.

The problem with that is the discovery of the unknown grouping labels on the dashboards.

Let me know how it goes, maybe we should add a section on the docs for this purpose or use case.

Thanks @cznewt!

**Comment by bthdimension** [comment]
Hey everyone, I would also be interested in a solution for this. We have lots of Kafka Clusters, each in their own namespace. Would be great to be able to filter by namespace. 
I'm using the PrometheusServiceLevel CRD to define queries. I added "by (namespace)" to each of my queries but the SLOTH metrics like slo:objective:ratio do not contain the namespace -> can't use it in Grafana.
Is there a solution for this?

**Comment by slok** [comment]
Hi @bthdimension!

There is no solution yet, however, I'm already thinking about how to tackle this problem, without being complex for the user.

**Comment by jleloup** [comment]
To add to the discussion, having a way to keep a Prometheus label as part of the aggregation would also help with keeping some extra labels in alerts.

For example I have some "environment" or "tenant_id" labels that I would like to keep in the alerts for routing purpose without having to explicitly set them in each alert definition.

**Comment by ishantanu** [comment]
Are there any plans to add `grouping` functionality as per this discussion? [Pyrra ](https://github.com/pyrra-dev/pyrra)has it where one can define grouping labels like

```yaml
grouping:
    - label1
    - label2
```

**Comment by ishantanu** [comment]
not stale

**Comment by snapydziuba** [comment]
@ishantanu even if not exposed by a grouping in the chart you can already do this.
Its important to keep `optimizedRules: false` otherwise the labels are not kept. This way we have for each SLO an extra exported_namespace label. (You have to add these to the dashboard queries)

```
      sli:
        raw:
          errorRatioQuery: |
            (
              sum by (exported_namespace) (
                rate(nginx_ingress_controller_requests{ingress="public-ingress", status=~"(5..|429)"}[{{.window}}])
              ) 
              / 
              (
                sum by (exported_namespace) (
                  rate(nginx_ingress_controller_requests{ingress="public-ingress"}[{{.window}}])
                ) > 0
              )
            ) 
            or 
            (
              sum by (exported_namespace) (
                rate(nginx_ingress_controller_requests{ingress="public-ingress", exported_namespace!=""}[{{.window}}])
              ) * 0
            )
```

And can then add this to the alerting
```

      alerting:
        name: "IngressHighErrorRate"
        labels:
          category: "availability"
        annotations:
          summary: "{{ $labels.exported_namespace }} error rate is above SLO"
          description: "{{ $labels.exported_namespace }} error rate is {{ $value | humanizePercentage }}"
        pageAlert:
          labels:
            severity: "critical"
        ticketAlert:
          labels:
            severity: "warning"
```
