### ISSUE TITLE
Changing labels breaks the recording rules

### ISSUE THREAD

**Issue by jimethn** [slok/sloth#311]
The top-level labels (`.spec.labels`) in PrometheusServiceLevel resources get carried over in various recording rules produced by SLOth e.g. `slo:sli_error:ratio_rate30d`. If you change any of those labels, while keeping other values the same, then the expressions in those rules will start to return more than one series (one with the old label, one with the new label), causing the recording rules to fail until the old label ages out. The error is "vector contains metrics with the same labelset after applying rule labels".

Steps to reproduce:

1. Install SLOth as a kubernetes operator using the PrometheusServiceLevel CRD
2. Define a PrometheusServiceLevel with a custom label and apply it to the cluster e.g.
```
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: test-slo
spec:
  service: "test"
  labels:
    owner: "qa"
  slos:
    - name: "overall-availability"
      objective: 99.9
      sli:
        events:
          <etc>
```
3. Change the label, e.g. set `owner: "bob"`, and apply it to the cluster
4. Some of the rules stop recording

Kindof a footgun but thought I'd report it. 😄
