### ISSUE TITLE
No page alerts for low objectives like `10`

### ISSUE THREAD

**Issue by AndreasSko** [slok/sloth#341]
I'm working on an SLO for a metric that reports resource usage in percent. My goal is to be alerted if the usage is high (like 90%) for a long period of time or even at the limit of 100%. So my idea was to set the objective at a low value of 10%, something like this:

```yaml
name: resource-percent
objective: 10
sli:
  raw:
    errorRatioQuery: "(avg_over_time(resource_usage_pct[{{.window}}])/100)" 
```

The problem that I see is that the page alert will never be triggered, as it checks for values > 1:
```
((slo:sli_error:ratio_rate5m{} > (14.4 * 0.9)) and ignoring(sloth_window) (slo:sli_error:ratio_rate1h{} > (14.4 * 0.9))) or ignoring(sloth_window) ((slo:sli_error:ratio_rate30m{} > (6 * 0.9)) and ignoring(sloth_window) (slo:sli_error:ratio_rate6h{} > (6 * 0.9)))
```

Similarly with the ticket alert, where at least the 2h and 1d checks will never trigger.
```
((slo:sli_error:ratio_rate2h{} > (3 * 0.9)) and ignoring(sloth_window) (slo:sli_error:ratio_rate1d{} > (3 * 0.9))) or ignoring(sloth_window) ((slo:sli_error:ratio_rate6h{} > (1 * 0.9)) and ignoring(sloth_window) (slo:sli_error:ratio_rate3d{} > (1 * 0.9)))
```

My current workaround is to adjust the metric and add an exponent of 8 to it, like this: 
```
errorRatioQuery: "(avg_over_time(resource_usage_pct[{{.window}}])/100) ^ 8"
```
and then set the objective to something like `95%`. 

The question that I have: Is it expected that low objectives might not trigger an alert at all because the allowed burn rate is just too high, meaning my SLO is just wrong? Or could it also be a bug or at least an edge case? My workaround is working fine, but I'm just wondering if there is a better approach for that problem.

Thank you for your help! :slightly_smiling_face:

**Comment by slok** [comment]
Hi!

I don't have all the context, however, think that SLOs are not the right tool for this type of alerting/problems. And as a side effect, you are having all these questions/problems, like if something doesn't fit correctly. You could accomplish that alert in a much simpler way with a simple Prometheus alerting rule:

```yaml
 - alert: ResourceUsageTooHigh
    expr: resource_usage_pct > 90
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: Resource usage is high.
      description: The usage of the resources has been too high for 1h.
```

If you want to continue using an SLO. You will need to think as events and stablish what is a good and a bad event:

> A measurement of the CPU usage over 90% is a wrong event.

So now you can start thinking as event-based SLOs:

```
Get me all the bad events in this time window (measurements of % usage that are over 90%)
/
Get me all the events in this time window (any measurement of % usage)
```
I have an example with a similar approach to wifi connection satisfaction SLOs: https://sloth.dev/examples/default/home-wifi/
