### ISSUE TITLE
Grafana generates 404

### ISSUE THREAD

**Issue by david-peters-aitch2o** [slok/sloth#405]
```
version: "prometheus/v1"
service: "my_test"
labels:
  owner: "CST"
  tier: "1"
slos:
  - name: "availability"
    objective: 99.50
    description: "SLO based on sucessful build probe"
    sli:
      events:
        error_query: sum(rate(probe_http_status_code{job="my_test",probe_http_status_code!~"2.."}[{{.window}}]))
        total_query: sum(rate(probe_duration_seconds{job="my_test"}[{{.window}}]))
    alerting:
      name: my_test _HighErrorRate
      labels:
        category: "availability"
      annotations:
        summary: "High failure rate on 'my_test' probe responses"
```

data is coming from BlackBox exporter

query 
```
1 - (max(slo:sli_error:ratio_rate${sli_window}{sloth_service="${service}", sloth_slo="${slo}"}) OR on() vector(0))
```
and
```
slo:objective:ratio{sloth_service="${service}", sloth_slo="${slo}"}
```
generating the SLI seems to work as expected

but it does generate a lot of 404 and other graphs don't update

```
Oct 12 23:12:09 grafana-grafana-server: logger=tsdb.prometheus t=2022-10-12T23:12:09.479073313+10:00 level=error msg="Exemplar query failed" query="1 - (max(slo:sli_error:ratio_rate5m{sloth_service=\"my_test\", sloth_slo=\"availability\"}) OR on() vector(0))" err="client_error: client error: 404"
```

and

```
Oct 12 23:14:45 grafana-grafana-server: logger=tsdb.prometheus t=2022-10-12T23:14:45.722543788+10:00 level=error msg="Exemplar query failed" query="1-(\n  sum_over_time(\n    (\n       slo:sli_error:ratio_rate1h{sloth_service=\"my_test\",sloth_slo=\"availability\"}\n       * on() group_left() (\n         month() == bool vector(10)\n       )\n    )[32d:1h]\n  )\n  / on(sloth_id)\n  (\n    slo:error_budget:ratio{sloth_service=\"my_test\",sloth_slo=\"availability\"} *on() group_left() (24 * days_in_month())\n  )\n)" err="client_error: client error: 404"
```
