### ISSUE TITLE
sloth generate directory

### ISSUE THREAD

**Issue by aaronstutzer** [slok/sloth#458]
I try to create a github action to generate the rules but I get an error for my `generate` command

job part of my github action config:
```
  generate-slo-job-1:
    name: Generate the SLOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download and setup generator binary
        run: |       
          wget https://github.com/slok/sloth/releases/download/v0.11.0/sloth-linux-amd64
          chmod +x sloth-linux-amd64
          ./sloth-linux-amd64 generate -i ./configuration/sloth/rules/ -o ./configuration/sloth/rules/_gen/
      - uses: EndBug/add-and-commit@v9
```

error message:
`error: "generate" command failed: invalid spec, could not load with any of the supported spec types`

what would be the correct command?
