### ISSUE TITLE
global alerting rule configuration

### ISSUE THREAD

**Issue by parkedwards** [slok/sloth#495]
hey there!

we currently use `sloth` to configure a number of SLOs.  currently, we specify `alerting:` configurations for each SLO, but they're all the same (same name, description text, etc.)

is there any way to specify a global alerting configuration?

**Comment by r3code** [comment]
Why they all the same? 
Can you show some examples?

**Comment by r3code** [comment]
I see. I'm struggling the same and the only way I see now is to create a jsonnet wrapper over sloth specs and generate specs from jsonnet slo specs. 
Or maybe it worth to extend the openslo spec support as it supports multiple alert conditions and refs to reuse them. Also they now support composite SLO, which allows you to have an aggregate SLO, continuing a sum weighted SLOs.

**Comment by parkedwards** [comment]
ahh interesting. yeah im avoiding jsonnet as much as possible, but maybe that's the only way to customize further

**Comment by r3code** [comment]
By the way, I ended up writing a small go tool to generate new sloth specs.
And another trick is to use yaml anchors 

```yaml
_common_blocks:
  alerting_disabled_def: &alerting_disabled_def
    page_alert:
      disable: true
    ticket_alert:
      disable: true
  alerting_enabled_def: &alerting_enabled_def
    name: "ServiceSLOViolation"
    labels:
      service: "{{ $labels.sloth_service }}"
      title: "{{ $labels.feature }}"
      feature: "{{ $labels.feature }}"
      slo: "{{ $labels.sloth_slo }}"
      sli_type: "{{ $labels.category }}"
      source: "slo"
      alert_class: slo_violation
      alert_type: symptom
    annotations:
      doc_url: https://kb.vseinstrumenti.ru/dosearchsite.action?cql=siteSearch%20~%20%22%5C%22{{ $labels.sloth_service }}-{{ $labels.sloth_slo }}%5C%22%22
      grafana_dashboard_id: slo-detail/ 
      grafana_dashboard_link: https://grafana/d/slo-detail?from=now-6h/m&to=now-1m/m&var-service={{ $labels.sloth_service }}&var-slo={{ $labels.sloth_slo }}
      grafana_min_zoom_hours: "6"
      grafana_panel_id: "18"
      grafana_variables: service,slo
      link: https://conflunce/dosearchsite.action?cql=siteSearch%20~%20%22ServiceSLOViolation%22
      runbook: docs/monitoring/slo-alerts/slo-violation-alert.md
    page_alert:
      labels:
        severity: critical
        slack_channel: *slack_alert_channel_primary
      annotations:
        summary: "Слишком высокая скорость расхода бюджета ошибок"
        description: |
          SLO: **{{ $labels.sloth_service }}-{{ $labels.sloth_slo }}**  \
          Your txt.
    ticket_alert:
      labels:
        severity: warning
        slack_channel: *slack_alert_channel_secondary
      annotations:
        summary: "Повышенная скорость расхода бюджета ошибок"
        description: |
          SLO: **{{ $labels.sloth_service }}-{{ $labels.sloth_slo }}**  \
          Your txt.
```
then in SLI section you use it 
```yaml
    alerting:
      <<: *alerting_enabled_def
# or 
    alerting:
      <<: *alerting_disabled_def
```
This gives me the flexibility to turn ON/OFF alarms.

And you can use a magic of `yq` to replace all alarm descriptions in sloth specs. I just realized that I need this as well :)
