### ISSUE TITLE
Per slo labels

### ISSUE THREAD

**Issue by freeseacher** [slok/sloth#497]
Hey. 
I want to mark slo with category label to separate special cases. 
Something like 

```
version: "prometheus/v1"
service: "home-wifi"
labels:
  cluster: "valhalla"
  component: "ubiquiti"
  context: "home"
slos:
  - name: "good-wifi-client-satisfaction"
    objective: 95
    description: "Will warn us that we don't have a good wifi at home."
    labels:
      category: availability
    sli:
      events:
        error_query: sum_over_time((count(unifipoller_client_satisfaction_ratio < 0.75))[{{.window}}:]) OR on() vector(0)
        total_query: sum_over_time((count(unifipoller_client_satisfaction_ratio))[{{.window}}:])
    alerting:
      name: GoodWifiClientSatisfaction
      page_alert:
        labels:
          severity: home
      ticket_alert:
        labels:
          severity: warning
```

Of cause we can global section but in this case there would be multiple files for single service. that is a bit inconvenient
