### ISSUE TITLE
Long run of slo and slo versioning

### ISSUE THREAD

**Issue by freeseacher** [slok/sloth#500]
From time to time we need to adjust queries or labels for slo.
as for now changing labels will break slo calculation for changed.

I propose to add label (?) `slo_version` to rules calculation and that label to the calculations of 
* slo:current_burn_rate:ratio
* slo:period_burn_rate:ratio
* slo:period_error_budget_remaining:ratio
* alerts
that would be enough to create different version of slo that can be tracked independently

**Comment by ervinb** [comment]
I worked around this limitation by simply renaming the SLO.

For example


```yaml
  slos:
      name: http-availability-rev-1 
      description: 99.5% of the requests should be successful for the user-facing API
      ...
```

becomes

```yaml
  slos:
      name: http-availability-rev-2
      description: 99.5% of the requests should be successful for the user-facing API
      ...
```

which results in a new SLO, while being able to track the previous one - the same behavior you'd get with having the `slo_version` label.
