### ISSUE TITLE
Overriding the `sloth_id` doesn't work

### ISSUE THREAD

**Issue by clarissalimab** [slok/sloth#513]
In certain circumstances, we wanted to manage the `sloth_id` to "reset" SLOs' budgets, like that:

```yaml
    - name: "example-slo"
      objective: 90
      description: "An example SLO"
      labels:
        sloth_id: custom-id
      sli:
        events: ...
```

If we set up that label, the recording rules correctly use the overridden `sloth_id`, but the queries for the Prometheus rules don't.

Is there a quick fix for that where we could make the queries use the `sloth_id` instead of the name of the SLO?
