### ISSUE TITLE
Ability to change metricSLOInfo default value

### ISSUE THREAD

**Issue by AndriiBurenko** [slok/sloth#538]
Add ability to change metricSLOInfo default value from vector(1) to vector(0).
This value is hardcoded in Go code.
Example AS IS:
```
    - expr: vector(1)
      labels:
        cmd: examplesgen.sh
        owner: myteam
        repo: myorg/myservice
        sloth_id: myservice-requests-availability
        sloth_mode: cli-gen-k8s
        sloth_objective: "99.9"
        sloth_service: myservice
        sloth_slo: requests-availability
        sloth_spec: sloth.slok.dev/v1
        sloth_version: dev
        tier: "2"
      record: sloth_slo_info
```
Example AS NEED:
```
    - expr: vector(0)
      labels:
        cmd: examplesgen.sh
        owner: myteam
        repo: myorg/myservice
        sloth_id: myservice-requests-availability
        sloth_mode: cli-gen-k8s
        sloth_objective: "99.9"
        sloth_service: myservice
        sloth_slo: requests-availability
        sloth_spec: sloth.slok.dev/v1
        sloth_version: dev
        tier: "2"
      record: sloth_slo_info
```
It's need in case of absence of metrics from application. Because now, if Sloth doesn't get metrics from Prometheus, the app is considered fully accessible. Such behavior is incorrect.

K8s cluster version: 1.29
Sloth image version: v0.11.0
