### ISSUE TITLE
 unknown field "spec.slos[0].alerting.page_alert"

### ISSUE THREAD

**Issue by lklkxcxc** [slok/sloth#539]
I installed sloth useing helm chart with crd，apply yaml:
```
# This example shows the same example as home-wifi.yml but using Sloth Kubernetes CRD.
# It will generate the Prometheus rules in a Kubernetes prometheus-operator PrometheusRules CRD.
#
# `sloth generate -i ./examples/plugin-k8s-home-wifi.yml` -p ./examples
#
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: sloth-slo-chaos-web
  namespace: monitoring
  labels:
    prometheus: prometheus
    role: alert-rules
    app: sloth
spec:
  service: "chaos-web"
  labels:
    owner: "ops"
    repo: "ops/chaos-web"
    tier: "2"
  slos:
    # We allow failing (5xx and 429) 1 request every 1000 requests (99.9%).
    - name: "requests-availability"
      objective: 99.9
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        plugin:
          id: "sloth-common/istio/v1/availability"
          options:
            namespace: "dev"
            service: "chaos-web"
            filter: request_protocol="http"
      alerting:
        name: MyServiceHighErrorRate
        labels:
          category: "availability"
        annotations:
          # Overwrite default Sloth SLO alert summmary on ticket and page alerts.
          summary: "High error rate on 'myservice' requests responses"
        page_alert:
          labels:
            severity: pageteam
            routing_key: myteam
        ticket_alert:
          labels:
            severity: "slack"
            slack_channel: "#alerts-myteam"
```
Output Errors:
```
Error from server (BadRequest): error when creating "plugin-k8s-getting-started.yml": PrometheusServiceLevel in version "v1" cannot be handled as a PrometheusServiceLevel: strict decoding error: unknown field "spec.slos[0].alerting.page_alert", unknown field "spec.slos[0].alerting.ticket_alert"
```
