### ISSUE TITLE
Is it possible to set SLOs for each namespace within a cluster and for the entire cluster?

### ISSUE THREAD

**Issue by githubeto** [slok/sloth#596]
I have created the following SLI.

```
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: sample
  namespace: <namespace>
spec:
  service: "sample"
  labels:
    owner: "SRE"
    repo: "skystyle/sample"
    tier: "1"
  slos:
    - name: "requests-availability"
      objective: 95.0
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        events:
          errorQuery: sum(rate(vm_http_request_duration_seconds_count{code=~"(4..|5..)"}[{{.window}}]))
          totalQuery: sum(rate(vm_http_request_duration_seconds_count[{{.window}}]))
      alerting:
        name: SlothHighErrorRate
        labels:
          category: "availability"
        annotations:
          summary: "High error rate on 'sample' requests responses"
        pageAlert:
          labels:
            severity: high
            routing_key: pagerduty
```

Is this targeting the namespace where the resource is installed?

In that case, how can I apply the same settings uniformly to all namespaces and monitor the entire cluster as a whole?
