### ISSUE TITLE
Multiple services per yaml file

### ISSUE THREAD

**Issue by KaiReichart** [slok/sloth#95]
Is it possible to generate multiple services in one `.yaml` file?  
In Kubernetes yamls it is common to have multiple definitions in one file, separated by `---`. This doesn't seem to work here atm.

Example:

```
# Source: slothgen/templates/sloth.yaml
version: "prometheus/v1"
service: "service1"
labels:
  owner: "itsme"
slos:
  - name: "myslo1"
    objective: 99.9
    description:" SLO"
    sli:
      events:
        error_query: sum(rate(http_server_requests_seconds{uri=~".*/XXX/.*",application="blablabla", status=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(http_server_requests_seconds{uri=~".*/XXX/.*", namespace="blablabla,application="occonnect-digen-apigateway"}[{{.window}}]))
    alerting:
      name: "alert"
      pageAlert:
        disabled: true
      ticketAlert:
        disabled: true
---
# Source: slothgen/templates/sloth.yaml
version: "prometheus/v1"
service: "myservice2"
labels:
  owner: "itsme"
slos:
  - name: "myslo1"
    objective: 99.9
    description: "SLO"
    sli:
      events:
        error_query: sum(rate(http_server_requests_seconds{uri=~".*/YYY/.*", namespace="blablabla", status=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(http_server_requests_seconds{uri=~".*/YYY/.*", namespace="blablabla"}[{{.window}}]))
    alerting:
      name: "alert"
      pageAlert:
        disabled: true
      ticketAlert:
        disabled: true

```

This would allow us to generate the sloth yamls with helm (or similar), and generate large amounts of Definitions like that.
